version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
    image: ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    stdin_open: true
    tty: true 